FROM oven/bun:latest
WORKDIR /app

COPY . .

ENV SLACK_CLIENT_TOKEN=${SLACK_CLIENT_TOKEN}
ENV SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
ENV SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}

ENV DATABASE_URL=${DATABASE_URL}

ENV HEADERS=${HEADERS}

ENV AIRTABLE_TOKEN=${AIRTABLE_TOKEN}
ENV AIRTABLE_BASE=${AIRTABLE_BASE}

RUN bun install

CMD ["bun", "run", "start"]

EXPOSE 3000